// Generated by AshTypescript
// Do not edit this file manually







// MemeGeneratorMemesLine Schema
export type MemeGeneratorMemesLineResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "text" | "align";
  id: string;
  text: string;
  align: string;
};



export type MemeGeneratorMemesLineAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "text" | "align";
  id: string;
  text: string;
  align: string;
};


export type MemeGeneratorMemesLineInputSchema = {
  id: string;
  text: string;
  align?: string;
};


// Meme Schema
export type MemeResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "label" | "renderDataUrl" | "createdAt" | "templateId";
  id: number;
  label: string | null;
  renderDataUrl: string | null;
  createdAt: number;
  templateId: number;
  lines: { __type: "Relationship"; __array: true; __resource: MemeGeneratorMemesLineResourceSchema; };
  template: { __type: "Relationship"; __resource: MemeTemplateResourceSchema; };
};



export type MemeAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "label" | "renderDataUrl" | "createdAt" | "templateId";
  id: number;
  label: string | null;
  renderDataUrl: string | null;
  createdAt: number;
  templateId: number;
  lines: { __type: "Relationship"; __array: true; __resource: MemeGeneratorMemesLineAttributesOnlySchema; };
};


// MemeGeneratorMemesPlacement Schema
export type MemeGeneratorMemesPlacementResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "label" | "x" | "y" | "width" | "height" | "align";
  id: string;
  label: string;
  x: number;
  y: number;
  width: number;
  height: number;
  align: string;
};



export type MemeGeneratorMemesPlacementAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "label" | "x" | "y" | "width" | "height" | "align";
  id: string;
  label: string;
  x: number;
  y: number;
  width: number;
  height: number;
  align: string;
};


export type MemeGeneratorMemesPlacementInputSchema = {
  id: string;
  label: string;
  x: number;
  y: number;
  width: number;
  height: number;
  align?: string;
};


// MemeTemplate Schema
export type MemeTemplateResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "imageUrl" | "width" | "height" | "boxCount" | "source" | "createdAt";
  id: number;
  name: string;
  imageUrl: string;
  width: number;
  height: number;
  boxCount: number;
  source: string;
  createdAt: number;
  placements: { __type: "Relationship"; __array: true; __resource: MemeGeneratorMemesPlacementResourceSchema; };
  aiPlacements: { __type: "Relationship"; __array: true; __resource: MemeGeneratorMemesPlacementResourceSchema; };
  memes: { __type: "Relationship"; __array: true; __resource: MemeResourceSchema; };
};



export type MemeTemplateAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "imageUrl" | "width" | "height" | "boxCount" | "source" | "createdAt";
  id: number;
  name: string;
  imageUrl: string;
  width: number;
  height: number;
  boxCount: number;
  source: string;
  createdAt: number;
  placements: { __type: "Relationship"; __array: true; __resource: MemeGeneratorMemesPlacementAttributesOnlySchema; };
  aiPlacements: { __type: "Relationship"; __array: true; __resource: MemeGeneratorMemesPlacementAttributesOnlySchema; };
};




export type MemeGeneratorMemesLineFilterInput = {
  and?: Array<MemeGeneratorMemesLineFilterInput>;
  or?: Array<MemeGeneratorMemesLineFilterInput>;
  not?: Array<MemeGeneratorMemesLineFilterInput>;

  id?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  text?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  align?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };



};
export type MemeFilterInput = {
  and?: Array<MemeFilterInput>;
  or?: Array<MemeFilterInput>;
  not?: Array<MemeFilterInput>;

  id?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  label?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  lines?: {
    eq?: Array<MemeGeneratorMemesLineResourceSchema>;
    notEq?: Array<MemeGeneratorMemesLineResourceSchema>;
    in?: Array<Array<MemeGeneratorMemesLineResourceSchema>>;
  };

  renderDataUrl?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  createdAt?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  templateId?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };


  template?: MemeTemplateFilterInput;

};
export type MemeGeneratorMemesPlacementFilterInput = {
  and?: Array<MemeGeneratorMemesPlacementFilterInput>;
  or?: Array<MemeGeneratorMemesPlacementFilterInput>;
  not?: Array<MemeGeneratorMemesPlacementFilterInput>;

  id?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  label?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  x?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  y?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  width?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  height?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  align?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };



};
export type MemeTemplateFilterInput = {
  and?: Array<MemeTemplateFilterInput>;
  or?: Array<MemeTemplateFilterInput>;
  not?: Array<MemeTemplateFilterInput>;

  id?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  imageUrl?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  width?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  height?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  boxCount?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  placements?: {
    eq?: Array<MemeGeneratorMemesPlacementResourceSchema>;
    notEq?: Array<MemeGeneratorMemesPlacementResourceSchema>;
    in?: Array<Array<MemeGeneratorMemesPlacementResourceSchema>>;
  };

  aiPlacements?: {
    eq?: Array<MemeGeneratorMemesPlacementResourceSchema>;
    notEq?: Array<MemeGeneratorMemesPlacementResourceSchema>;
    in?: Array<Array<MemeGeneratorMemesPlacementResourceSchema>>;
  };

  source?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  createdAt?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };


  memes?: MemeFilterInput;

};


// Utility Types

// Resource schema constraint
export type TypedSchema = {
  __type: "Resource" | "TypedMap" | "Union";
  __primitiveFields: string;
};

// Utility type to convert union to intersection
export type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;

// Helper type to infer union field values, avoiding duplication between array and non-array unions
export type InferUnionFieldValue<
  UnionSchema extends { __type: "Union"; __primitiveFields: any },
  FieldSelection extends any[],
> = UnionToIntersection<
  {
    [FieldIndex in keyof FieldSelection]: FieldSelection[FieldIndex] extends UnionSchema["__primitiveFields"]
      ? FieldSelection[FieldIndex] extends keyof UnionSchema
        ? { [P in FieldSelection[FieldIndex]]: UnionSchema[FieldSelection[FieldIndex]] }
        : never
      : FieldSelection[FieldIndex] extends Record<string, any>
        ? {
            [UnionKey in keyof FieldSelection[FieldIndex]]: UnionKey extends keyof UnionSchema
              ? NonNullable<UnionSchema[UnionKey]> extends { __array: true; __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
                ? FieldSelection[FieldIndex][UnionKey] extends any[]
                  ? Array<
                      UnionToIntersection<
                        {
                          [FieldIdx in keyof FieldSelection[FieldIndex][UnionKey]]: FieldSelection[FieldIndex][UnionKey][FieldIdx] extends TypedMapFields
                            ? FieldSelection[FieldIndex][UnionKey][FieldIdx] extends keyof NonNullable<UnionSchema[UnionKey]>
                              ? { [P in FieldSelection[FieldIndex][UnionKey][FieldIdx]]: NonNullable<UnionSchema[UnionKey]>[P] }
                              : never
                            : never;
                        }[number]
                      >
                    > | null
                  : never
                : NonNullable<UnionSchema[UnionKey]> extends { __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
                  ? FieldSelection[FieldIndex][UnionKey] extends any[]
                    ? UnionToIntersection<
                        {
                          [FieldIdx in keyof FieldSelection[FieldIndex][UnionKey]]: FieldSelection[FieldIndex][UnionKey][FieldIdx] extends TypedMapFields
                            ? FieldSelection[FieldIndex][UnionKey][FieldIdx] extends keyof NonNullable<UnionSchema[UnionKey]>
                              ? { [P in FieldSelection[FieldIndex][UnionKey][FieldIdx]]: NonNullable<UnionSchema[UnionKey]>[P] }
                              : never
                            : never;
                        }[number]
                      > | null
                    : never
                  : NonNullable<UnionSchema[UnionKey]> extends TypedSchema
                    ? InferResult<NonNullable<UnionSchema[UnionKey]>, FieldSelection[FieldIndex][UnionKey]>
                    : never
              : never;
          }
        : never;
  }[number]
>;

export type HasComplexFields<T extends TypedSchema> = keyof Omit<
  T,
  "__primitiveFields" | "__type" | T["__primitiveFields"]
> extends never
  ? false
  : true;

export type ComplexFieldKeys<T extends TypedSchema> = keyof Omit<
  T,
  "__primitiveFields" | "__type" | T["__primitiveFields"]
>;

export type LeafFieldSelection<T extends TypedSchema> = T["__primitiveFields"];

export type ComplexFieldSelection<T extends TypedSchema> = {
  [K in ComplexFieldKeys<T>]?: T[K] extends {
    __type: "Relationship";
    __resource: infer Resource;
  }
    ? NonNullable<Resource> extends TypedSchema
      ? UnifiedFieldSelection<NonNullable<Resource>>[]
      : never
    : T[K] extends {
          __type: "ComplexCalculation";
          __returnType: infer ReturnType;
        }
      ? T[K] extends { __args: infer Args }
        ? NonNullable<ReturnType> extends TypedSchema
          ? {
              args: Args;
              fields: UnifiedFieldSelection<NonNullable<ReturnType>>[];
            }
          : { args: Args }
        : NonNullable<ReturnType> extends TypedSchema
          ? { fields: UnifiedFieldSelection<NonNullable<ReturnType>>[] }
          : never
      : T[K] extends { __type: "TypedMap" }
        ? NonNullable<T[K]> extends TypedSchema
          ? UnifiedFieldSelection<NonNullable<T[K]>>[]
          : never
        : T[K] extends { __type: "Union"; __primitiveFields: infer PrimitiveFields }
          ? T[K] extends { __array: true }
            ? (PrimitiveFields | {
                [UnionKey in keyof Omit<T[K], "__type" | "__primitiveFields" | "__array">]?: NonNullable<T[K][UnionKey]> extends { __type: "TypedMap"; __primitiveFields: any }
                  ? NonNullable<T[K][UnionKey]>["__primitiveFields"][]
                  : NonNullable<T[K][UnionKey]> extends TypedSchema
                    ? UnifiedFieldSelection<NonNullable<T[K][UnionKey]>>[]
                    : never;
              })[]
            : (PrimitiveFields | {
                [UnionKey in keyof Omit<T[K], "__type" | "__primitiveFields">]?: NonNullable<T[K][UnionKey]> extends { __type: "TypedMap"; __primitiveFields: any }
                  ? NonNullable<T[K][UnionKey]>["__primitiveFields"][]
                  : NonNullable<T[K][UnionKey]> extends TypedSchema
                    ? UnifiedFieldSelection<NonNullable<T[K][UnionKey]>>[]
                    : never;
              })[]
            : NonNullable<T[K]> extends TypedSchema
              ? UnifiedFieldSelection<NonNullable<T[K]>>[]
              : never;
};

// Main type: Use explicit base case detection to prevent infinite recursion
export type UnifiedFieldSelection<T extends TypedSchema> =
  HasComplexFields<T> extends false
    ? LeafFieldSelection<T> // Base case: only primitives, no recursion
    : LeafFieldSelection<T> | ComplexFieldSelection<T>; // Recursive case

export type InferFieldValue<
  T extends TypedSchema,
  Field,
> = Field extends T["__primitiveFields"]
  ? Field extends keyof T
    ? { [K in Field]: T[Field] }
    : never
  : Field extends Record<string, any>
    ? {
        [K in keyof Field]: K extends keyof T
          ? T[K] extends {
              __type: "Relationship";
              __resource: infer Resource;
            }
            ? NonNullable<Resource> extends TypedSchema
              ? T[K] extends { __array: true }
                ? Array<InferResult<NonNullable<Resource>, Field[K]>>
                : null extends Resource
                  ? InferResult<NonNullable<Resource>, Field[K]> | null
                  : InferResult<NonNullable<Resource>, Field[K]>
            : never
          : T[K] extends {
                __type: "ComplexCalculation";
                __returnType: infer ReturnType;
              }
            ? NonNullable<ReturnType> extends TypedSchema
              ? null extends ReturnType
                ? InferResult<NonNullable<ReturnType>, Field[K]["fields"]> | null
                : InferResult<NonNullable<ReturnType>, Field[K]["fields"]>
              : ReturnType
            : NonNullable<T[K]> extends { __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
              ? NonNullable<T[K]> extends { __array: true }
                ? Field[K] extends any[]
                  ? null extends T[K]
                    ? Array<
                        UnionToIntersection<
                          {
                            [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                              ? E extends TypedMapFields
                                ? E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                                : E extends Record<string, any>
                                  ? {
                                      [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                        ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                          ? null extends NonNullable<T[K]>[NestedKey]
                                            ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                            : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                          : never
                                        : never;
                                    }
                                  : E extends keyof NonNullable<T[K]>
                                    ? { [P in E]: NonNullable<T[K]>[P] }
                                    : never
                              : never;
                          }[number]
                        >
                      > | null
                    : Array<
                        UnionToIntersection<
                          {
                            [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                              ? E extends TypedMapFields
                                ? E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                                : E extends Record<string, any>
                                  ? {
                                      [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                        ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                          ? null extends NonNullable<T[K]>[NestedKey]
                                            ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                            : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                          : never
                                        : never;
                                    }
                                  : E extends keyof NonNullable<T[K]>
                                    ? { [P in E]: NonNullable<T[K]>[P] }
                                    : never
                              : never;
                          }[number]
                        >
                      >
                  : never
                : Field[K] extends any[]
                  ? null extends T[K]
                    ? UnionToIntersection<
                        {
                          [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                            ? E extends TypedMapFields
                              ? E extends keyof NonNullable<T[K]>
                                ? { [P in E]: NonNullable<T[K]>[P] }
                                : never
                              : E extends Record<string, any>
                                ? {
                                    [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                      ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                        ? null extends NonNullable<T[K]>[NestedKey]
                                          ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                          : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                        : never
                                      : never;
                                  }
                                : E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                            : never;
                        }[number]
                      > | null
                    : UnionToIntersection<
                        {
                          [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                            ? E extends TypedMapFields
                              ? E extends keyof T[K]
                                ? { [P in E]: T[K][P] }
                                : never
                              : E extends Record<string, any>
                                ? {
                                    [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                      ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                        ? null extends NonNullable<T[K]>[NestedKey]
                                          ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                          : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                        : never
                                      : never;
                                  }
                                : E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                            : never;
                        }[number]
                      >
                  : never
              : T[K] extends { __type: "Union"; __primitiveFields: any }
                ? T[K] extends { __array: true }
                  ? Field[K] extends any[]
                    ? null extends T[K]
                      ? Array<InferUnionFieldValue<T[K], Field[K]>> | null
                      : Array<InferUnionFieldValue<T[K], Field[K]>>
                    : never
                  : Field[K] extends any[]
                    ? null extends T[K]
                      ? InferUnionFieldValue<T[K], Field[K]> | null
                      : InferUnionFieldValue<T[K], Field[K]>
                    : never
                  : NonNullable<T[K]> extends TypedSchema
                    ? null extends T[K]
                      ? InferResult<NonNullable<T[K]>, Field[K]> | null
                      : InferResult<NonNullable<T[K]>, Field[K]>
                    : never
          : never;
      }
    : never;

export type InferResult<
  T extends TypedSchema,
  SelectedFields extends UnifiedFieldSelection<T>[] | undefined,
> = SelectedFields extends undefined
  ? {}
  : SelectedFields extends []
  ? {}
  : SelectedFields extends UnifiedFieldSelection<T>[]
  ? UnionToIntersection<
      {
        [K in keyof SelectedFields]: InferFieldValue<T, SelectedFields[K]>;
      }[number]
    >
  : {};

// Pagination conditional types
// Checks if a page configuration object has any pagination parameters
export type HasPaginationParams<Page> =
  Page extends { offset: any } ? true :
  Page extends { after: any } ? true :
  Page extends { before: any } ? true :
  false;

// Infer which pagination type is being used from the page config
export type InferPaginationType<Page> =
  Page extends { offset: any } ? "offset" :
  Page extends { after: any } | { before: any } ? "keyset" :
  never;

// Returns either non-paginated (array) or paginated result based on page params
// For single pagination type support (offset-only or keyset-only)
// @ts-ignore
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export type ConditionalPaginatedResult<
  Page,
  RecordType,
  PaginatedType
> = Page extends undefined
  ? RecordType
  : HasPaginationParams<Page> extends true
    ? PaginatedType
    : RecordType;

// For actions supporting both offset and keyset pagination
// Infers the specific pagination type based on which params were passed
export type ConditionalPaginatedResultMixed<
  Page,
  RecordType,
  OffsetType,
  KeysetType
> = Page extends undefined
  ? RecordType
  : HasPaginationParams<Page> extends true
    ? InferPaginationType<Page> extends "offset"
      ? OffsetType
      : InferPaginationType<Page> extends "keyset"
        ? KeysetType
        : OffsetType | KeysetType  // Fallback to union if can't determine
    : RecordType;

export type SuccessDataFunc<T extends (...args: any[]) => Promise<any>> = Extract<
  Awaited<ReturnType<T>>,
  { success: true }
>["data"];


export type ErrorData<T extends (...args: any[]) => Promise<any>> = Extract<
  Awaited<ReturnType<T>>,
  { success: false }
>["errors"];

/**
 * Represents an error from an unsuccessful RPC call.
 *
 * This type matches the error structure defined in the AshTypescript.Rpc.Error protocol.
 *
 * @example
 * const error: AshRpcError = {
 *   type: "invalid_changes",
 *   message: "Invalid value for field %{field}",
 *   shortMessage: "Invalid changes",
 *   vars: { field: "email" },
 *   fields: ["email"],
 *   path: ["user", "email"],
 *   details: { suggestion: "Provide a valid email address" }
 * }
 */
export type AshRpcError = {
  /** Machine-readable error type (e.g., "invalid_changes", "not_found") */
  type: string;
  /** Full error message (may contain template variables like %{key}) */
  message: string;
  /** Concise version of the message */
  shortMessage: string;
  /** Variables to interpolate into the message template */
  vars: Record<string, any>;
  /** List of affected field names (for field-level errors) */
  fields: string[];
  /** Path to the error location in the data structure */
  path: string[];
  /** Optional map with extra details (e.g., suggestions, hints) */
  details?: Record<string, any>;
}

/**
 * Represents the result of a validation RPC call.
 *
 * All validation actions return this same structure, indicating either
 * successful validation or a list of validation errors.
 *
 * @example
 * // Successful validation
 * const result: ValidationResult = { success: true };
 *
 * // Failed validation
 * const result: ValidationResult = {
 *   success: false,
 *   errors: [
 *     {
 *       type: "required",
 *       message: "is required",
 *       shortMessage: "Required field",
 *       vars: { field: "email" },
 *       fields: ["email"],
 *       path: []
 *     }
 *   ]
 * };
 */
export type ValidationResult =
  | { success: true }
  | { success: false; errors: AshRpcError[]; };





// Helper Functions

/**
 * Configuration options for action RPC requests
 */
export interface ActionConfig {
  // Request data
  input?: Record<string, any>;
  identity?: any;
  fields?: Array<string | Record<string, any>>; // Field selection
  filter?: Record<string, any>; // Filter options (for reads)
  sort?: string; // Sort options
  page?:
    | {
        // Offset-based pagination
        limit?: number;
        offset?: number;
        count?: boolean;
      }
    | {
        // Keyset pagination
        limit?: number;
        after?: string;
        before?: string;
      };

  // Metadata
  metadataFields?: ReadonlyArray<string>;

  // HTTP customization
  headers?: Record<string, string>; // Custom headers
  fetchOptions?: RequestInit; // Fetch options (signal, cache, etc.)
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Multitenancy
  tenant?: string; // Tenant parameter

  // Hook context
  hookCtx?: Record<string, any>;
}




/**
 * Gets the CSRF token from the page's meta tag
 * Returns null if no CSRF token is found
 */
export function getPhoenixCSRFToken(): string | null {
  return document
    ?.querySelector("meta[name='csrf-token']")
    ?.getAttribute("content") || null;
}

/**
 * Builds headers object with CSRF token for Phoenix applications
 * Returns headers object with X-CSRF-Token (if available)
 */
export function buildCSRFHeaders(headers: Record<string, string> = {}): Record<string, string> {
  const csrfToken = getPhoenixCSRFToken();
  if (csrfToken) {
    headers["X-CSRF-Token"] = csrfToken;
  }

  return headers;
}

/**
 * Internal helper function for making action RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ActionConfig
 */
export async function executeActionRpcRequest<T>(
  payload: Record<string, any>,
  config: ActionConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/run", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}











export type CreateMemeInput = {
  templateId: number;
  label?: string | null;
  lines?: Array<MemeGeneratorMemesLineInputSchema>;
  renderDataUrl?: string | null;
};


type CreateMemeSchema = Omit<MemeResourceSchema, 'template'> & {
  template: { __type: "Relationship"; __resource: MemeTemplateAttributesOnlySchema; };
};

export type CreateMemeFields = UnifiedFieldSelection<CreateMemeSchema>[];

export type InferCreateMemeResult<
  Fields extends CreateMemeFields | undefined,
> = InferResult<CreateMemeSchema, Fields>;

export type CreateMemeResult<Fields extends CreateMemeFields | undefined = undefined> = | { success: true; data: InferCreateMemeResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Meme
 *
 * @ashActionType :create
 */
export async function createMeme<Fields extends CreateMemeFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateMemeInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateMemeResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_meme",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateMemeResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}



export type DestroyMemeResult = | { success: true; data: {}; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Delete a Meme
 *
 * @ashActionType :destroy
 */
export async function destroyMeme(
  config: {
  tenant?: string;
  identity: number;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<DestroyMemeResult> {
  const payload = {
    action: "destroy_meme",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeActionRpcRequest<DestroyMemeResult>(
    payload,
    config
  );
}


export type GetMemeInput = {
  id: number;
};


type GetMemeSchema = Omit<MemeResourceSchema, 'template'> & {
  template: { __type: "Relationship"; __resource: MemeTemplateAttributesOnlySchema; };
};

export type GetMemeFields = UnifiedFieldSelection<GetMemeSchema>[];
export type InferGetMemeResult<
  Fields extends GetMemeFields,
> = InferResult<GetMemeSchema, Fields>;

export type GetMemeResult<Fields extends GetMemeFields> = | { success: true; data: InferGetMemeResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Meme records
 *
 * @ashActionType :read
 */
export async function getMeme<Fields extends GetMemeFields>(
  config: {
  tenant?: string;
  input: GetMemeInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetMemeResult<Fields>> {
  const payload = {
    action: "get_meme",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GetMemeResult<Fields>>(
    payload,
    config
  );
}



type ListMemesSchema = Omit<MemeResourceSchema, 'template'> & {
  template: { __type: "Relationship"; __resource: MemeTemplateAttributesOnlySchema; };
};

export type ListMemesFields = UnifiedFieldSelection<ListMemesSchema>[];


export type InferListMemesResult<
  Fields extends ListMemesFields | undefined,
  Page extends ListMemesConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<ListMemesSchema, Fields>>, {
  results: Array<InferResult<ListMemesSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<ListMemesSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type ListMemesConfig = {
  tenant?: string;
  fields: ListMemesFields;
  filter?: MemeFilterInput;
  sort?: string;
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListMemesResult<Fields extends ListMemesFields, Page extends ListMemesConfig["page"] = undefined> = | { success: true; data: InferListMemesResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Meme records
 *
 * @ashActionType :read
 */
export async function listMemes<Fields extends ListMemesFields, Config extends ListMemesConfig = ListMemesConfig>(
  config: Config & { fields: Fields }
): Promise<ListMemesResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_memes",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListMemesResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


export type UpdateMemeInput = {
  templateId?: number;
  label?: string | null;
  lines?: Array<MemeGeneratorMemesLineInputSchema>;
  renderDataUrl?: string | null;
};


type UpdateMemeSchema = Omit<MemeResourceSchema, 'template'> & {
  template: { __type: "Relationship"; __resource: MemeTemplateAttributesOnlySchema; };
};

export type UpdateMemeFields = UnifiedFieldSelection<UpdateMemeSchema>[];

export type InferUpdateMemeResult<
  Fields extends UpdateMemeFields | undefined,
> = InferResult<UpdateMemeSchema, Fields>;

export type UpdateMemeResult<Fields extends UpdateMemeFields | undefined = undefined> = | { success: true; data: InferUpdateMemeResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Meme
 *
 * @ashActionType :update
 */
export async function updateMeme<Fields extends UpdateMemeFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: number;
  input: UpdateMemeInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<UpdateMemeResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "update_meme",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<UpdateMemeResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


export type CreateTemplateInput = {
  id: number;
  name: string;
  imageUrl: string;
  width: number;
  height: number;
  boxCount: number;
  placements?: Array<MemeGeneratorMemesPlacementInputSchema>;
  aiPlacements?: Array<MemeGeneratorMemesPlacementInputSchema> | null;
  source?: string;
};

export type CreateTemplateFields = UnifiedFieldSelection<MemeTemplateResourceSchema>[];

export type InferCreateTemplateResult<
  Fields extends CreateTemplateFields | undefined,
> = InferResult<MemeTemplateResourceSchema, Fields>;

export type CreateTemplateResult<Fields extends CreateTemplateFields | undefined = undefined> = | { success: true; data: InferCreateTemplateResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Template
 *
 * @ashActionType :create
 */
export async function createTemplate<Fields extends CreateTemplateFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateTemplateInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateTemplateResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_template",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateTemplateResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}



export type DestroyTemplateResult = | { success: true; data: {}; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Delete a Template
 *
 * @ashActionType :destroy
 */
export async function destroyTemplate(
  config: {
  tenant?: string;
  identity: number;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<DestroyTemplateResult> {
  const payload = {
    action: "destroy_template",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeActionRpcRequest<DestroyTemplateResult>(
    payload,
    config
  );
}


export type GetTemplateInput = {
  id: number;
};

export type GetTemplateFields = UnifiedFieldSelection<MemeTemplateResourceSchema>[];
export type InferGetTemplateResult<
  Fields extends GetTemplateFields,
> = InferResult<MemeTemplateResourceSchema, Fields>;

export type GetTemplateResult<Fields extends GetTemplateFields> = | { success: true; data: InferGetTemplateResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Template records
 *
 * @ashActionType :read
 */
export async function getTemplate<Fields extends GetTemplateFields>(
  config: {
  tenant?: string;
  input: GetTemplateInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetTemplateResult<Fields>> {
  const payload = {
    action: "get_template",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GetTemplateResult<Fields>>(
    payload,
    config
  );
}


export type ListTemplatesFields = UnifiedFieldSelection<MemeTemplateResourceSchema>[];


export type InferListTemplatesResult<
  Fields extends ListTemplatesFields | undefined,
  Page extends ListTemplatesConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<MemeTemplateResourceSchema, Fields>>, {
  results: Array<InferResult<MemeTemplateResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<MemeTemplateResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type ListTemplatesConfig = {
  tenant?: string;
  fields: ListTemplatesFields;
  filter?: MemeTemplateFilterInput;
  sort?: string;
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListTemplatesResult<Fields extends ListTemplatesFields, Page extends ListTemplatesConfig["page"] = undefined> = | { success: true; data: InferListTemplatesResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Template records
 *
 * @ashActionType :read
 */
export async function listTemplates<Fields extends ListTemplatesFields, Config extends ListTemplatesConfig = ListTemplatesConfig>(
  config: Config & { fields: Fields }
): Promise<ListTemplatesResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_templates",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListTemplatesResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


export type UpdateTemplateInput = {
  name?: string;
  imageUrl?: string;
  width?: number;
  height?: number;
  boxCount?: number;
  placements?: Array<MemeGeneratorMemesPlacementInputSchema>;
  aiPlacements?: Array<MemeGeneratorMemesPlacementInputSchema> | null;
  source?: string;
};

export type UpdateTemplateFields = UnifiedFieldSelection<MemeTemplateResourceSchema>[];

export type InferUpdateTemplateResult<
  Fields extends UpdateTemplateFields | undefined,
> = InferResult<MemeTemplateResourceSchema, Fields>;

export type UpdateTemplateResult<Fields extends UpdateTemplateFields | undefined = undefined> = | { success: true; data: InferUpdateTemplateResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Template
 *
 * @ashActionType :update
 */
export async function updateTemplate<Fields extends UpdateTemplateFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: number;
  input: UpdateTemplateInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<UpdateTemplateResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "update_template",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<UpdateTemplateResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


