# SPDX-FileCopyrightText: 2025 ash_typescript contributors <https://github.com/ash-project/ash_typescript/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshTypescript.TypedController.CodegenTest do
  use ExUnit.Case

  @moduletag :ash_typescript

  setup_all do
    typescript =
      AshTypescript.TypedController.Codegen.generate(
        router: AshTypescript.Test.ControllerResourceTestRouter
      )

    %{typescript: typescript}
  end

  describe "multi-mount code generation" do
    setup do
      typescript =
        AshTypescript.TypedController.Codegen.generate(
          router: AshTypescript.Test.ControllerResourceMultiMountRouter
        )

      %{typescript: typescript}
    end

    test "generates prefixed path helpers for each scope", %{typescript: typescript} do
      assert String.contains?(typescript, "export function adminAuthPath(")
      assert String.contains?(typescript, "export function appAuthPath(")
    end

    test "generates prefixed action functions for each scope", %{typescript: typescript} do
      assert String.contains?(typescript, "export async function adminLogin(")
      assert String.contains?(typescript, "export async function appLogin(")
    end

    test "generates prefixed input types for each scope", %{typescript: typescript} do
      assert String.contains?(typescript, "export type AdminLoginInput = {")
      assert String.contains?(typescript, "export type AppLoginInput = {")
    end

    test "generates prefixed PATCH functions for each scope", %{typescript: typescript} do
      assert String.contains?(typescript, "export async function adminUpdateProvider(")
      assert String.contains?(typescript, "export async function appUpdateProvider(")
    end

    test "generates prefixed input types for PATCH routes", %{typescript: typescript} do
      assert String.contains?(typescript, "export type AdminUpdateProviderInput = {")
      assert String.contains?(typescript, "export type AppUpdateProviderInput = {")
    end

    test "generates prefixed path helpers for mutation routes", %{typescript: typescript} do
      assert String.contains?(typescript, "export function adminLoginPath(")
      assert String.contains?(typescript, "export function appLoginPath(")
      assert String.contains?(typescript, "export function adminLogoutPath(")
      assert String.contains?(typescript, "export function appLogoutPath(")
    end

    test "does not generate unprefixed helpers when multi-mounted", %{typescript: typescript} do
      refute Regex.match?(~r/function authPath\(/, typescript)
      refute Regex.match?(~r/function login\(/, typescript)
    end
  end

  describe "ambiguous mount error" do
    test "raises when router has duplicate mounts without as: options" do
      assert_raise RuntimeError, ~r/don't have unique `as:` options/, fn ->
        AshTypescript.TypedController.Codegen.generate(
          router: AshTypescript.Test.ControllerResourceAmbiguousRouter
        )
      end
    end
  end

  describe "GET route path helpers" do
    test "generates non-empty TypeScript output", %{typescript: typescript} do
      assert typescript != ""
      assert String.contains?(typescript, "// This file is auto-generated by AshTypescript")
    end

    test "generates path helper for auth route", %{typescript: typescript} do
      assert String.contains?(typescript, "export function authPath(")
      assert String.contains?(typescript, "return \"/auth\"")
    end

    test "generates path helper for provider_page route with path param and query param", %{
      typescript: typescript
    } do
      assert String.contains?(typescript, "export function providerPagePath(")
      assert String.contains?(typescript, "path: { provider: string }")
      assert String.contains?(typescript, "query?: { tab?: string }")
    end

    test "GET path helper with path params uses path object in URL template", %{
      typescript: typescript
    } do
      [_, after_provider_page] =
        String.split(typescript, "export function providerPagePath(", parts: 2)

      [provider_page_body | _] = String.split(after_provider_page, "\n}\n", parts: 2)
      assert String.contains?(provider_page_body, "${path.provider}")
    end

    test "generates path helper for search route with required query param", %{
      typescript: typescript
    } do
      assert String.contains?(typescript, "export function searchPath(")
      assert String.contains?(typescript, "query: { q: string; page?: number }")
    end

    test "generates URLSearchParams for GET routes with query params", %{typescript: typescript} do
      assert String.contains?(typescript, "new URLSearchParams()")
      assert String.contains?(typescript, "searchParams.set(")
      assert String.contains?(typescript, "searchParams.toString()")
    end

    test "GET path helpers do not generate async functions", %{typescript: typescript} do
      # Extract individual path helper functions (authPath, providerPagePath, searchPath)
      # and verify none are async
      for path_fn <- ["authPath()", "providerPagePath(", "searchPath("] do
        assert String.contains?(typescript, "export function #{path_fn}")
        refute String.contains?(typescript, "export async function #{path_fn}")
      end
    end

    test "generates JSDoc for path helpers", %{typescript: typescript} do
      assert String.contains?(typescript, "Path helper for /auth")
      assert String.contains?(typescript, "Path helper for /auth/providers/:provider")
    end
  end

  describe "POST route action functions" do
    test "generates typed input type for login action", %{typescript: typescript} do
      assert String.contains?(typescript, "export type LoginInput = {")
      assert String.contains?(typescript, "code: string;")
      assert String.contains?(typescript, "rememberMe?: boolean;")
    end

    test "generates async function for login with input param", %{typescript: typescript} do
      assert String.contains?(typescript, "export async function login(")
      assert String.contains?(typescript, "input: LoginInput")
      assert String.contains?(typescript, "Promise<Response>")
    end

    test "login function sends POST with JSON body", %{typescript: typescript} do
      assert String.contains?(typescript, "method: \"POST\"")
      assert String.contains?(typescript, "body: JSON.stringify(input)")
    end

    test "generates async function for logout without input param", %{typescript: typescript} do
      assert String.contains?(typescript, "export async function logout(")
      assert String.contains?(typescript, "config?: {")
      refute String.contains?(typescript, "LogoutInput")
    end

    test "logout function sends POST without body", %{typescript: typescript} do
      [_, after_logout] = String.split(typescript, "export async function logout(", parts: 2)
      [logout_body | _] = String.split(after_logout, "\n}\n", parts: 2)
      refute String.contains?(logout_body, "body:")
    end

    test "action functions accept optional config with headers", %{typescript: typescript} do
      assert String.contains?(typescript, "config?: { headers?: Record<string, string> }")
    end

    test "generates JSDoc for action functions", %{typescript: typescript} do
      assert String.contains?(typescript, "POST /auth/login")
      assert String.contains?(typescript, "POST /auth/logout")
    end

    test "generates path helper alongside login action function", %{typescript: typescript} do
      assert String.contains?(typescript, "export function loginPath(")
      assert String.contains?(typescript, "return \"/auth/login\"")
    end

    test "generates path helper alongside logout action function", %{typescript: typescript} do
      assert String.contains?(typescript, "export function logoutPath(")
      assert String.contains?(typescript, "return \"/auth/logout\"")
    end
  end

  describe "path param validation" do
    test "raises when path param has no matching DSL argument" do
      route_info = %{
        source_module: AshTypescript.Test.Session,
        controller: AshTypescript.Test.SessionController,
        route: %{
          name: :broken,
          method: :get,
          arguments: [],
          run: fn conn, _params -> conn end,
          description: nil,
          deprecated: nil
        },
        path: "/items/:id",
        method: :get,
        path_params: [:id],
        scope_prefix: nil
      }

      assert_raise RuntimeError, ~r/don't have matching DSL arguments/, fn ->
        AshTypescript.TypedController.Codegen.validate_path_param_arguments!([route_info])
      end
    end
  end

  describe "PATCH route with path params and input" do
    test "generates typed input type for update_provider action excluding path params", %{
      typescript: typescript
    } do
      assert String.contains?(typescript, "export type UpdateProviderInput = {")
      assert String.contains?(typescript, "enabled: boolean;")
      assert String.contains?(typescript, "displayName?: string;")
      # provider is a path param and should not be in the input type
      refute String.contains?(typescript, "UpdateProviderInput = {\n  provider")
    end

    test "generates async function with path and input params", %{typescript: typescript} do
      assert String.contains?(typescript, "export async function updateProvider(")
      assert String.contains?(typescript, "path: { provider: string }")
      assert String.contains?(typescript, "input: UpdateProviderInput")
      assert String.contains?(typescript, "Promise<Response>")
    end

    test "update_provider function sends PATCH with JSON body", %{typescript: typescript} do
      assert String.contains?(typescript, "method: \"PATCH\"")
    end

    test "update_provider function uses path object for URL template", %{typescript: typescript} do
      assert String.contains?(typescript, "${path.provider}")
    end

    test "generates JSDoc for PATCH action", %{typescript: typescript} do
      assert String.contains?(typescript, "PATCH /auth/providers/:provider")
    end

    test "generates path helper alongside PATCH action function", %{typescript: typescript} do
      assert String.contains?(typescript, "export function updateProviderPath(")
      assert String.contains?(typescript, "path: { provider: string }")
      assert String.contains?(typescript, "Path helper for /auth/providers/:provider")
    end
  end

  describe "typed_controller_path_params_style: :args" do
    setup do
      previous = Application.get_env(:ash_typescript, :typed_controller_path_params_style)
      Application.put_env(:ash_typescript, :typed_controller_path_params_style, :args)

      typescript =
        AshTypescript.TypedController.Codegen.generate(
          router: AshTypescript.Test.ControllerResourceTestRouter
        )

      on_exit(fn ->
        if previous do
          Application.put_env(:ash_typescript, :typed_controller_path_params_style, previous)
        else
          Application.delete_env(:ash_typescript, :typed_controller_path_params_style)
        end
      end)

      %{typescript: typescript}
    end

    test "GET path helper uses flat positional args for path params", %{typescript: typescript} do
      assert String.contains?(typescript, "export function providerPagePath(provider: string,")
      refute String.contains?(typescript, "providerPagePath(path:")
    end

    test "GET path helper URL template accesses params directly", %{typescript: typescript} do
      [_, after_provider_page] =
        String.split(typescript, "export function providerPagePath(", parts: 2)

      [provider_page_body | _] = String.split(after_provider_page, "\n}\n", parts: 2)
      assert String.contains?(provider_page_body, "${provider}")
      refute String.contains?(provider_page_body, "${path.provider}")
    end

    test "mutation action function uses flat positional args for path params", %{
      typescript: typescript
    } do
      assert String.contains?(
               typescript,
               "export async function updateProvider(provider: string,"
             )

      refute String.contains?(typescript, "updateProvider(path:")
    end

    test "mutation action function URL template accesses params directly", %{
      typescript: typescript
    } do
      [_, after_update_provider] =
        String.split(typescript, "export async function updateProvider(", parts: 2)

      [update_provider_body | _] = String.split(after_update_provider, "\n}\n", parts: 2)
      assert String.contains?(update_provider_body, "${provider}")
      refute String.contains?(update_provider_body, "${path.provider}")
    end

    test "mutation path helper uses flat positional args", %{typescript: typescript} do
      assert String.contains?(typescript, "export function updateProviderPath(provider: string)")
      refute String.contains?(typescript, "updateProviderPath(path:")
    end
  end

  describe "typed_controller_mode: :paths_only" do
    setup do
      previous = Application.get_env(:ash_typescript, :typed_controller_mode)
      Application.put_env(:ash_typescript, :typed_controller_mode, :paths_only)

      typescript =
        AshTypescript.TypedController.Codegen.generate(
          router: AshTypescript.Test.ControllerResourceTestRouter
        )

      on_exit(fn ->
        if previous do
          Application.put_env(:ash_typescript, :typed_controller_mode, previous)
        else
          Application.delete_env(:ash_typescript, :typed_controller_mode)
        end
      end)

      %{typescript: typescript}
    end

    test "generates path helpers for all routes", %{typescript: typescript} do
      assert String.contains?(typescript, "export function authPath(")
      assert String.contains?(typescript, "export function providerPagePath(")
      assert String.contains?(typescript, "export function searchPath(")
      assert String.contains?(typescript, "export function loginPath(")
      assert String.contains?(typescript, "export function logoutPath(")
      assert String.contains?(typescript, "export function updateProviderPath(")
      assert String.contains?(typescript, "export function echoParamsPath(")
    end

    test "does not generate async action functions", %{typescript: typescript} do
      refute String.contains?(typescript, "async function")
      refute String.contains?(typescript, "fetch(")
      refute String.contains?(typescript, "Promise<Response>")
    end

    test "does not generate input types", %{typescript: typescript} do
      refute String.contains?(typescript, "export type LoginInput")
      refute String.contains?(typescript, "export type UpdateProviderInput")
      refute String.contains?(typescript, "export type EchoParamsInput")
    end

    test "still generates query params for GET routes", %{typescript: typescript} do
      assert String.contains?(typescript, "query?: { tab?: string }")
      assert String.contains?(typescript, "query: { q: string; page?: number }")
    end
  end
end
