defmodule MemeGenerator.Repo.Migrations.CreateMemesTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:memes, primary_key: false) do
      add :template_id,
          references(:meme_templates, column: :id, name: "memes_template_id_fkey", type: :bigint),
          null: false

      add :created_at, :bigint, null: false
      add :render_data_url, :text
      add :lines, {:array, :map}, null: false, default: []
      add :label, :text
      add :id, :bigserial, null: false, primary_key: true
    end

    create table(:meme_templates, primary_key: false) do
      add :created_at, :bigint, null: false
      add :source, :text, null: false
      add :ai_placements, {:array, :map}
      add :placements, {:array, :map}, null: false, default: []
      add :box_count, :bigint, null: false
      add :height, :bigint, null: false
      add :width, :bigint, null: false
      add :image_url, :text, null: false
      add :name, :text, null: false
      add :id, :bigint, null: false, primary_key: true
    end
  end

  def down do
    drop table(:meme_templates)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `memes` table without the `memes_template_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:memes)
  end
end
