defmodule MemeGenerator.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:memes) do
      add :updated_at, :bigint, null: false, default: 0
      add :archived_at, :utc_datetime_usec
    end

    alter table(:meme_templates) do
      add :updated_at, :bigint, null: false, default: 0
    end

    execute("UPDATE memes SET updated_at = COALESCE(created_at * 1000, 0) WHERE updated_at = 0")

    execute(
      "UPDATE meme_templates SET updated_at = COALESCE(created_at * 1000, 0) WHERE updated_at = 0"
    )
  end

  def down do
    alter table(:meme_templates) do
      remove :updated_at
    end

    alter table(:memes) do
      remove :archived_at
      remove :updated_at
    end
  end
end
